app:
  name: jenkins
  namespace: jenkins-ci

image:
  repository: jenkins/jenkins
  tag: "2.443-jdk21"
  digest: ""
  pullPolicy: Always

rbac:
  serviceAccountName: jenkins-admin
  rules: 
    - apiGroups: [""]
      resources: ["*"]
      verbs: ["*"]

server:
  local: true

  replicaCount: 1

  securityContext:
    fsGroup: 1000
    runAsUser: 1000

  resources:
    limits: 
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "1Gi"
      cpu: "1000m"

  labels: {}
  annotations: {}

  tolerations:
    - key: jenkins
      operator: Equal
      value: "true"
      effect: NoSchedule

  nodeSelector:
     nodepool: "jenkins-pool"

  persistentVolume:
    enabled: true

    storageClass: "standard"

    accessMode:     
      - ReadWriteOnce

    storageSize: "5Gi"

    labels: {}
    annotations: {}

    # existingClaim: ""
    # existingVolume: ""

    selector: {}

  service: 
    type: NodePort
    port: 8080
    nodePort: 32000


